print("Hello world!")
print("Hello world!")
print("Hello sun!")
print("Hello sky!")
print("Hello World! Pass this test, please.")
print("Hello world!", end="")
print("Hello sun!", end="!!")
print("Hello sky!", end="!!!\n")
print("Hello world! Pass this test, please.", end="!!!\n")
